services:
  postgres:
    image: postgres:latest
    container_name: property_listings_postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - property_network

  redis:
    image: redis:latest
    container_name: property_listings_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - property_network

volumes:
  postgres_data:
  redis_data:

networks:
  property_network:
    driver: bridge
